export abstract class Op {
    static OP_TOP_UP_BALANCE = 0x593e3893;
    static OP_INIT_CHANNEL = 0x79ae99b5;
    static OP_COOPERATIVE_CLOSE = 0xd2b1eeeb;
    static OP_COOPERATIVE_COMMIT = 0x076bfdf1;
    static OP_START_UNCOOPERATIVE_CLOSE = 0x8175e15d;
    static OP_CHALLENGE_QUARANTINEED_STATE = 0x9a77c0db;
    static OP_SETTLE_CONDITIONALS = 0x56c39b4c;
    static OP_FINISH_UNCOOPERATIVE_CLOSE = 0x25432a91;
    static OP_CHANNEL_CLOSED = 0xdddc88ba;
    static OP_CHANNEL_WITHDRAW = 0xa32f0b3c;
    static OP_JETTON_TRANSFER = 0xf8a7ea5;
    static OP_JETTON_TAKE_WALLET_ADDRESS = 0xd1735400;
    static OP_JETTON_PROVIDE_WALLET_ADDRESS = 0x2c76b973;
    static OP_JETTON_TRANSFER_NOTIFICATION = 0x7362d09c;
    static OP_EXCESSES = 0xd53276db;
}

export abstract class Errors {
    static ERROR_ALREADY_INITED = 100;
    static ERROR_NOT_AUTHORIZED = 101;
    static ERROR_INCORRECT_INITIAL_BALANCE = 102;
    static ERROR_WRONG_TAG = 104;
    static ERROR_OUTDATED_STATE = 105;
    static ERROR_QUARANTINE_ALREADY_ACTIVE = 106;
    static ERROR_NO_QUARANTINED_STATE = 107;
    static ERROR_SEQNO_REGRESS = 108;
    static ERROR_UNAUTHORIZED_CHALLENGE = 109;
    static ERROR_QUARANTINE_NOT_FINISHED = 110;
    static ERROR_TOO_LATE_FOR_QUARANTINE_CHALLENGE = 111;
    static ERROR_TOO_LATE_TO_SETTLE_CONDITIONALS = 112;
    static ERROR_TOO_EARLY_TO_CLOSE = 113;
    static ERROR_WRONG_CHANNEL_ID = 114;
    static ERROR_INCORRECT_CONDITIONALS_PROOF = 115;
    static ERROR_INCORRECT_UPDATED_PROOF = 116;
    static ERROR_NOT_INITED = 117;
    static ERROR_NOT_ENOUGH_BALANCE = 118;
    static ERROR_AMOUNT_NOT_COVERS_FEE = 119;
    static ERROR_INVALID_CURRENCY_TYPE = 120;
    static ERROR_INVALID_EC_ID = 121;
    static ERROR_NOT_ENOUGH_CONTRACT_BALANCE = 122;
    static ERROR_NOT_ENOUGH_MONEY_FOR_INIT_STORAGE = 123;
    static ERROR_JETTON_WALLET_ALREADY_INSTALLED = 124;
    static ERROR_QUARANTINEE_ALREADY_CHALLENGED = 125;
    static ERROR_INCORRECT_SUMMARIZED_BALANCE = 126;
    static ERROR_WITHDRAW_REGRESS = 127;
}

export abstract class Tags {
    static TAG_INIT_CHANNEL = 0x481ebc44;
    static TAG_COOPERATIVE_CLOSE = 0x8243e9a3;
    static TAG_COOPERATIVE_COMMIT = 0x4a390cac;
    static TAG_START_UNCOOPERATIVE_CLOSE = 0x8c623692;
    static TAG_CHALLENGE_QUARANTINEED_STATE = 0xb8a21379;
    static TAG_SETTLE_CONDITIONALS = 0x14588aab;
    static TAG_STATE = 0x43685374;
}

export enum ChannelState {
    STATE_UNINITED = 0,
    STATE_OPEN,
    STATE_CLOSURE_STARTED,
    STATE_SETTLING_CONDITIONALS,
    STATE_AWAITING_FINALIZATION
}
